name: pr-check

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: test
          check_filenames: true
          check_hidden: false

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: ["1.4.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install package dependencies
        run: |
          poetry install
      - name: Run mypy
        run: |
          poetry run mypy .
      - name: Run ruff
        run: |
          poetry run ruff .
      - name: Run pyright
        run: |
          poetry run pyright .
      - name: Run unit tests
        run: |
          poetry run pytest tests/unit_tests/ -vv
      - name: Execute worker and dependency
        run: docker compose -f tests/execute_sdk/docker-compose.yml up -d
