name: pr-check

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/ruff-check@0.0.263

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: test
          check_filenames: true
          check_hidden: false

  unitest:
    name: Format & Unit tests check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Test with pytest
        run: |
          coverage run -m pytest -v
