name: PyPi Frinx-Python-SDK update

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish-sdk:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.4.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry version bump
        run: poetry version $(git describe --tags --abbrev=0)
      - name: poetry publish
        run: poetry publish -u "__token__" -p "${{ secrets.PYPI_TOKEN }}" --build
