name: PyPi Frinx-Python-SDK update

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish-sdk:
    name: Build and publish frinx python sdk
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Generate version
        run: |
          VERSION=$(echo "${{ github.ref }}" | rev | cut -d '/' -f 1 | rev | sed 's|^v||g')
          sed -i "s|VERSION = '0.0.0'|VERSION = '${VERSION}'|g" frinx/__init__.py
          cat frinx/__init__.py | grep VERSION

      - name: install
        run: pip install -U twine build packaging

      - name: Build
        run: python -m build .

      - name: Check build
        run: twine check dist/*

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
